# PT站点自动签到工具配置文件示例
# 复制此文件为 config.yml 并修改相应配置

# 基础配置
max_workers   : 1                    # 最大工作线程数
user_agent    : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
get_messages  : true                # 是否获取站点消息
get_details   : true                 # 是否获取详细信息
cookie_backup : true               # 是否备份Cookie

# 百度OCR配置 (可选，用于验证码识别)
aipocr:
  app_id     : ''              # 百度OCR应用ID
  api_key    : ''             # 百度OCR API Key
  secret_key : ''

# 浏览器自动化配置
browser_automation:
  enabled: true                       # 是否启用浏览器自动化
  headless: false                      # 是否使用无头模式
  timeout: 30                         # 操作超时时间（秒）
  browser_path: ''                    # 自定义浏览器路径
  user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36'
  browser_arguments:                  # 额外的浏览器启动参数
    # - '--disable-web-security'
    - '--disable-features=VizDisplayCompositor'

# 站点配置
sites:
  # 示例站点配置 - 简单模式 (仅Cookie)
  # site_name: 'your_cookie_string_here'

  # 示例站点配置 - 详细模式
  # site_name:
  #   cookie: 'your_cookie_string_here'
  #   username: 'your_username'
  #   comment: 'daily_sign_in'
  #   user_agent: 'custom_user_agent'  # 可选，覆盖全局设置

  # 实际配置示例 (请替换为你的真实信息)
  # dmhy:
  #   cookie: 'your_dmhy_cookie_here'
  #   username: 'your_username'
  #   comment: '每日签到'

  # byr: 'your_byr_cookie_here'