# PT站点自动签到工具配置文件示例
# 复制此文件为 config.yml 并修改相应配置

# 基础配置
max_workers   : 1                    # 最大工作线程数
user_agent    : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
get_messages  : true                # 是否获取站点消息
get_details   : true                 # 是否获取详细信息
cookie_backup : true               # 是否备份Cookie

# 百度OCR配置 (可选，用于验证码识别)
aipocr:
  app_id     : ''              # 百度OCR应用ID
  api_key    : ''             # 百度OCR API Key
  secret_key : ''

# FlareSolverr配置 (可选，用于绕过Cloudflare保护)
flaresolverr:
  server_url: 'http://localhost:8191'  # FlareSolverr服务器地址
  timeout: 60                          # 请求超时时间（秒）
  enabled_sites:                       # 启用FlareSolverr的站点列表（如果该键值为"*"，则表明全部启用）
    - btschool                         # 示例：为btschool站点启用
    - hdsky                            # HDSky现在也使用FlareSolverr
    # - "*"                            # 取消注释此行可为所有站点启用FlareSolverr

# 站点配置
sites:
  # 示例站点配置 - 简单模式 (仅Cookie)
  # site_name: 'your_cookie_string_here'

  # 示例站点配置 - 详细模式
  # hdsky:
  #   cookie: 'your_cookie_string_here'
  #   join_date: 'xxxx-xx-xx'

# 请求方式说明：
# - default: 标准HTTP请求（最快，适用于大多数站点）
# - flaresolverr: 通过FlareSolverr绕过Cloudflare保护

# 优先级：
# 1. 站点配置中的request_method
# 2. 全局FlareSolverr配置（enabled_sites列表或"*"）
# 3. 默认使用标准请求